package com.colonylink.colonylink;

import net.minecraft.client.gui.GuiGraphics;
import java.util.Base64;

/**
 * Pixel-perfect procedural skin for the Warehouse Link Terminal — 100% g.fill(), zero textures.
 * GENERATED from the original lossless PNG assets by gen/generate.py (do not hand-edit; re-run
 * the generator if the source art changes). Each skin = an ARGB palette + a packed list of
 * solid-colour rectangles (7 bytes/rect: x.hi x.lo y.hi y.lo w h paletteIndex). Fully transparent
 * zones emit no rectangle; partial-alpha edges keep their alpha and blend via g.fill. Renders
 * crisp at any GUI scale because nothing is sampled from a texture.
 */
public final class TerminalSkin {
    private TerminalSkin() {}

    public static final class Skin {
        public final int w, h;
        final int[] rx, ry, rw, rh, rc;
        final int[] pal;
        Skin(int w, int h, int[] pal, String b64) {
            this.w = w; this.h = h; this.pal = pal;
            byte[] d = Base64.getDecoder().decode(b64);
            int n = d.length / 7;
            rx = new int[n]; ry = new int[n]; rw = new int[n]; rh = new int[n]; rc = new int[n];
            for (int i = 0, p = 0; i < n; i++) {
                int xh = d[p++] & 0xFF, xl = d[p++] & 0xFF;
                int yh = d[p++] & 0xFF, yl = d[p++] & 0xFF;
                rx[i] = (xh << 8) | xl;
                ry[i] = (yh << 8) | yl;
                rw[i] = d[p++] & 0xFF;
                rh[i] = d[p++] & 0xFF;
                rc[i] = d[p++] & 0xFF;
            }
        }
    }

    /** Draw a skin with its top-left corner at (ox, oy), in GUI coordinates. */
    public static void draw(GuiGraphics g, Skin s, int ox, int oy) {
        for (int i = 0; i < s.rx.length; i++) {
            int x = ox + s.rx[i], y = oy + s.ry[i];
            g.fill(x, y, x + s.rw[i], y + s.rh[i], s.pal[s.rc[i]]);
        }
    }

    /**
     * Dessin "fluide" facon AE2 : on supprime la bande verticale [cutTop, cutBot[
     * (les lignes de slots du milieu) et on remonte de {@code dy} px tout ce qui se
     * trouve sous {@code cutBot} (cadre bas des panneaux, connecteur, bloc craft +
     * inventaire). Les coordonnees cutTop/cutBot sont LOCALES au skin (origine 0,0).
     * Les rectangles qui chevauchent la coupe sont scindes proprement. Avec
     * dy = 0 (cutTop == cutBot) le rendu est strictement identique a draw().
     */
    public static void drawCut(GuiGraphics g, Skin s, int ox, int oy,
                               int cutTop, int cutBot, int dy) {
        for (int i = 0; i < s.rx.length; i++) {
            int x1 = ox + s.rx[i];
            int x2 = x1 + s.rw[i];
            int y1 = s.ry[i];
            int y2 = y1 + s.rh[i];
            int col = s.pal[s.rc[i]];
            if (y1 < cutTop)                                   // portion haute (ancree en haut)
                g.fill(x1, oy + y1, x2, oy + Math.min(y2, cutTop), col);
            if (y2 > cutBot) {                                 // portion basse, remontee de dy
                int by1 = Math.max(y1, cutBot);
                g.fill(x1, oy + by1 - dy, x2, oy + y2 - dy, col);
            }
        }
    }

    private static final int[] PAL_BG = {
            0xFFADB0C4, 0xFFCBCCD4, 0xFF9A9FB4, 0xFFF2F2F2, 0xFF413F54, 0xFF696D88, 0xFF878FA5, 0xFFF9FAFB,
            0xFF94929D, 0xFFC5C6D0, 0xFF4D4D67, 0x1B3A384E, 0xFFE1E2E6, 0xF8555366, 0xFF696777, 0xFFD4D5DB,
            0xFFFFFFFF, 0xFFCFCFD7, 0xFF868693, 0x0A46455A, 0xF84A495E, 0xFF9DA2B7, 0xFFA1A7BC, 0xFF545368,
            0x1B3E3B50, 0x22434257, 0x0C4A495E, 0x08434257, 0x1346455A, 0x18414054, 0x1D413F54
    };
    private static final String DAT_BG =
            "AAAAAMMBBADIAAAUAQgA4QAAwwEEAAAAAQHtBAABAAHBAQMAwgABAe0EAMgAAQETCADJAAESAQcA2wABARMIAOEAAQHtBADiAAHBAQMBowABAe0EAAEAAgHpAwACAAK/DAEAwQACAekDAMkAAgERBwDKAAIQAQIA2gACAREHAOIAAgHpAwDjAAK/DAEBogACAekDAMoAAxAPAAACAA4F3AEABwAOgAEDAIcADjoQAQDjAA4F3AEA6AAOgAEDAWgADjoQAQAHAA8BCwMACAAPfgIFAIYADwELAwDoAA8BCwMA6QAPfgIFAWcADwELAwAIABF+CAIA6QARfggCAMoAEhABBwDJABMB2AgAygATAdcHAMsAEw4BCQDZABMB1wcA2gATAdgIAMsAFAHWCQDMABQM1gEA2AAUAdYJAAgAGX4BAwDpABl+AQMABwAagAQBAOgAGoAEAQAHAB6iAQMAqQAeCcwBALIAHgYBAwC4AB4JzAEA6AAeogEDAYoAHgnMAQGTAB4GAQMBmQAeCcwBAAcAHwHGAwAIAB8QAQIAGAAfAsUBABoAHxABAgAqAB8CxQEALAAfEAECADwAHwLFAQA+AB8QAQIATgAfAsUBAFAAHxABAgBgAB8CxQEAYgAfEAECAHIAHwLFAQB0AB8QAQIAhAAfAsUBAIYAHxABAgCWAB8CxQEAmAAfEAECAKgAHwHGAwCyAB8BxgMAswAfBAIFALcAHwHGAwDoAB8BxgMA6QAfEAECAPkAHwLFAQD7AB8QAQIBCwAfAsUBAQ0AHxABAgEdAB8CxQEBHwAfEAECAS8AHwLFAQExAB8QAQIBQQAfAsUBAUMAHxABAgFTAB8CxQEBVQAfEAECAWUAHwLFAQFnAB8QAQIBdwAfAsUBAXkAHxABAgGJAB8BxgMBkwAfAcYDAZQAHwQCBQGYAB8BxgMACAAgEA8AABoAIBAPAAAsACAQDwAAPgAgEA8AAFAAIBAPAABiACAQDwAAdAAgEA8AAIYAIBAPAACYACAQDwAA6QAgEA8AAPsAIBAPAAENACAQDwABHwAgEA8AATEAIBAPAAFDACAQDwABVQAgEA8AAWcAIBAPAAF5ACAQDwAAswAhBMMCAZQAIQTDAgAIAC8QAgEAGgAvEAIBACwALxACAQA+AC8QAgEAUAAvEAIBAGIALxACAQB0AC8QAgEAhgAvEAIBAJgALxACAQDpAC8QAgEA+wAvEAIBAQ0ALxACAQEfAC8QAgEBMQAvEAIBAUMALxACAQFVAC8QAgEBZwAvEAIBAXkALxACAQAIADEQAQIAGgAxEAECACwAMRABAgA+ADEQAQIAUAAxEAECAGIAMRABAgB0ADEQAQIAhgAxEAECAJgAMRABAgDpADEQAQIA+wAxEAECAQ0AMRABAgEfADEQAQIBMQAxEAECAUMAMRABAgFVADEQAQIBZwAxEAECAXkAMRABAgAIADIQDwAAGgAyEA8AACwAMhAPAAA+ADIQDwAAUAAyEA8AAGIAMhAPAAB0ADIQDwAAhgAyEA8AAJgAMhAPAADpADIQDwAA+wAyEA8AAQ0AMhAPAAEfADIQDwABMQAyEA8AAUMAMhAPAAFVADIQDwABZwAyEA8AAXkAMhAPAAAIAEEQAgEAGgBBEAIBACwAQRACAQA+AEEQAgEAUABBEAIBAGIAQRACAQB0AEEQAgEAhgBBEAIBAJgAQRACAQDpAEEQAgEA+wBBEAIBAQ0AQRACAQEfAEEQAgEBMQBBEAIBAUMAQRACAQFVAEEQAgEBZwBBEAIBAXkAQRACAQAIAEMQAQIAGgBDEAECACwAQxABAgA+AEMQAQIAUABDEAECAGIAQxABAgB0AEMQAQIAhgBDEAECAJgAQxABAgDpAEMQAQIA+wBDEAECAQ0AQxABAgEfAEMQAQIBMQBDEAECAUMAQxABAgFVAEMQAQIBZwBDEAECAXkAQxABAgAIAEQQDwAAGgBEEA8AACwARBAPAAA+AEQQDwAAUABEEA8AAGIARBAPAAB0AEQQDwAAhgBEEA8AAJgARBAPAADpAEQQDwAA+wBEEA8AAQ0ARBAPAAEfAEQQDwABMQBEEA8AAUMARBAPAAFVAEQQDwABZwBEEA8AAXkARBAPAAAIAFMQAgEAGgBTEAIBACwAUxACAQA+AFMQAgEAUABTEAIBAGIAUxACAQB0AFMQAgEAhgBTEAIBAJgAUxACAQDpAFMQAgEA+wBTEAIBAQ0AUxACAQEfAFMQAgEBMQBTEAIBAUMAUxACAQFVAFMQAgEBZwBTEAIBAXkAUxACAQAIAFUQAQIAGgBVEAECACwAVRABAgA+AFUQAQIAUABVEAECAGIAVRABAgB0AFUQAQIAhgBVEAECAJgAVRABAgDpAFUQAQIA+wBVEAECAQ0AVRABAgEfAFUQAQIBMQBVEAECAUMAVRABAgFVAFUQAQIBZwBVEAECAXkAVRABAgAIAFYQDwAAGgBWEA8AACwAVhAPAAA+AFYQDwAAUABWEA8AAGIAVhAPAAB0AFYQDwAAhgBWEA8AAJgAVhAPAADpAFYQDwAA+wBWEA8AAQ0AVhAPAAEfAFYQDwABMQBWEA8AAUMAVhAPAAFVAFYQDwABZwBWEA8AAXkAVhAPAAAIAGUQAgEAGgBlEAIBACwAZRACAQA+AGUQAgEAUABlEAIBAGIAZRACAQB0AGUQAgEAhgBlEAIBAJgAZRACAQDpAGUQAgEA+wBlEAIBAQ0AZRACAQEfAGUQAgEBMQBlEAIBAUMAZRACAQFVAGUQAgEBZwBlEAIBAXkAZRACAQAIAGcQAQIAGgBnEAECACwAZxABAgA+AGcQAQIAUABnEAECAGIAZxABAgB0AGcQAQIAhgBnEAECAJgAZxABAgDpAGcQAQIA+wBnEAECAQ0AZxABAgEfAGcQAQIBMQBnEAECAUMAZxABAgFVAGcQAQIBZwBnEAECAXkAZxABAgAIAGgQDwAAGgBoEA8AACwAaBAPAAA+AGgQDwAAUABoEA8AAGIAaBAPAAB0AGgQDwAAhgBoEA8AAJgAaBAPAADpAGgQDwAA+wBoEA8AAQ0AaBAPAAEfAGgQDwABMQBoEA8AAUMAaBAPAAFVAGgQDwABZwBoEA8AAXkAaBAPAAAIAHcQAgEAGgB3EAIBACwAdxACAQA+AHcQAgEAUAB3EAIBAGIAdxACAQB0AHcQAgEAhgB3EAIBAJgAdxACAQDpAHcQAgEA+wB3EAIBAQ0AdxACAQEfAHcQAgEBMQB3EAIBAUMAdxACAQFVAHcQAgEBZwB3EAIBAXkAdxACAQAIAHkQAQIAGgB5EAECACwAeRABAgA+AHkQAQIAUAB5EAECAGIAeRABAgB0AHkQAQIAhgB5EAECAJgAeRABAgDpAHkQAQIA+wB5EAECAQ0AeRABAgEfAHkQAQIBMQB5EAECAUMAeRABAgFVAHkQAQIBZwB5EAECAXkAeRABAgAIAHoQDwAAGgB6EA8AACwAehAPAAA+AHoQDwAAUAB6EA8AAGIAehAPAAB0AHoQDwAAhgB6EA8AAJgAehAPAADpAHoQDwAA+wB6EA8AAQ0AehAPAAEfAHoQDwABMQB6EA8AAUMAehAPAAFVAHoQDwABZwB6EA8AAXkAehAPAAAIAIkQAgEAGgCJEAIBACwAiRACAQA+AIkQAgEAUACJEAIBAGIAiRACAQB0AIkQAgEAhgCJEAIBAJgAiRACAQDpAIkQAgEA+wCJEAIBAQ0AiRACAQEfAIkQAgEBMQCJEAIBAUMAiRACAQFVAIkQAgEBZwCJEAIBAXkAiRACAQAIAIsQAQIAGgCLEAECACwAixABAgA+AIsQAQIAUACLEAECAGIAixABAgB0AIsQAQIAhgCLEAECAJgAixABAgDpAIsQAQIA+wCLEAECAQ0AixABAgEfAIsQAQIBMQCLEAECAUMAixABAgFVAIsQAQIBZwCLEAECAXkAixABAgAIAIwQDwAAGgCMEA8AACwAjBAPAAA+AIwQDwAAUACMEA8AAGIAjBAPAAB0AIwQDwAAhgCMEA8AAJgAjBAPAADpAIwQDwAA+wCMEA8AAQ0AjBAPAAEfAIwQDwABMQCMEA8AAUMAjBAPAAFVAIwQDwABZwCMEA8AAXkAjBAPAAAIAJsQAgEAGgCbEAIBACwAmxACAQA+AJsQAgEAUACbEAIBAGIAmxACAQB0AJsQAgEAhgCbEAIBAJgAmxACAQDpAJsQAgEA+wCbEAIBAQ0AmxACAQEfAJsQAgEBMQCbEAIBAUMAmxACAQFVAJsQAgEBZwCbEAIBAXkAmxACAQAIAJ0QAQIAGgCdEAECACwAnRABAgA+AJ0QAQIAUACdEAECAGIAnRABAgB0AJ0QAQIAhgCdEAECAJgAnRABAgDpAJ0QAQIA+wCdEAECAQ0AnRABAgEfAJ0QAQIBMQCdEAECAUMAnRABAgFVAJ0QAQIBZwCdEAECAXkAnRABAgAIAJ4QDwAAGgCeEA8AACwAnhAPAAA+AJ4QDwAAUACeEA8AAGIAnhAPAAB0AJ4QDwAAhgCeEA8AAJgAnhAPAADpAJ4QDwAA+wCeEA8AAQ0AnhAPAAEfAJ4QDwABMQCeEA8AAUMAnhAPAAFVAJ4QDwABZwCeEA8AAXkAnhAPAAAIAK0QAgEAGgCtEAIBACwArRACAQA+AK0QAgEAUACtEAIBAGIArRACAQB0AK0QAgEAhgCtEAIBAJgArRACAQDpAK0QAgEA+wCtEAIBAQ0ArRACAQEfAK0QAgEBMQCtEAIBAUMArRACAQFVAK0QAgEBZwCtEAIBAXkArRACAQAIAK8QAQIAGgCvEAECACwArxABAgA+AK8QAQIAUACvEAECAGIArxABAgB0AK8QAQIAhgCvEAECAJgArxABAgDpAK8QAQIA+wCvEAECAQ0ArxABAgEfAK8QAQIBMQCvEAECAUMArxABAgFVAK8QAQIBZwCvEAECAXkArxABAgAIALAQDwAAGgCwEA8AACwAsBAPAAA+ALAQDwAAUACwEA8AAGIAsBAPAAB0ALAQDwAAhgCwEA8AAJgAsBAPAADpALAQDwAA+wCwEA8AAQ0AsBAPAAEfALAQDwABMQCwEA8AAUMAsBAPAAFVALAQDwABZwCwEA8AAXkAsBAPAAAIAL8QAgEAGgC/EAIBACwAvxACAQA+AL8QAgEAUAC/EAIBAGIAvxACAQB0AL8QAgEAhgC/EAIBAJgAvxACAQDpAL8QAgEA+wC/EAIBAQ0AvxACAQEfAL8QAgEBMQC/EAIBAUMAvxACAQFVAL8QAgEBZwC/EAIBAXkAvxACAQAIAMEQAQIAGgDBEAECACwAwRABAgA+AMEQAQIAUADBEAECAGIAwRABAgB0AMEQAQIAhgDBEAECAJgAwRABAgDpAMEQAQIA+wDBEAECAQ0AwRABAgEfAMEQAQIBMQDBEAECAUMAwRABAgFVAMEQAQIBZwDBEAECAXkAwRABAgAIAMIQDwAAGgDCEA8AACwAwhAPAAA+AMIQDwAAUADCEA8AAGIAwhAPAAB0AMIQDwAAhgDCEA8AAJgAwhAPAADpAMIQDwAA+wDCEA8AAQ0AwhAPAAEfAMIQDwABMQDCEA8AAUMAwhAPAAFVAMIQDwABZwDCEA8AAXkAwhAPAAAIANEQAgEAGgDREAIBACwA0RACAQA+ANEQAgEAUADREAIBAGIA0RACAQB0ANEQAgEAhgDREAIBAJgA0RACAQDpANEQAgEA+wDREAIBAQ0A0RACAQEfANEQAgEBMQDREAIBAUMA0RACAQFVANEQAgEBZwDREAIBAXkA0RACAQAIANMQAQIAGgDTEAECACwA0xABAgA+ANMQAQIAUADTEAECAGIA0xABAgB0ANMQAQIAhgDTEAECAJgA0xABAgDpANMQAQIA+wDTEAECAQ0A0xABAgEfANMQAQIBMQDTEAECAUMA0xABAgFVANMQAQIBZwDTEAECAXkA0xABAgAIANQQDwAAGgDUEA8AACwA1BAPAAA+ANQQDwAAUADUEA8AAGIA1BAPAAB0ANQQDwAAhgDUEA8AAJgA1BAPAADpANQQDwAA+wDUEA8AAQ0A1BAPAAEfANQQDwABMQDUEA8AAUMA1BAPAAFVANQQDwABZwDUEA8AAXkA1BAPAAAIAOMQAQEAGgDjEAEBACwA4xABAQA+AOMQAQEAUADjEAEBAGIA4xABAQB0AOMQAQEAhgDjEAEBAJgA4xABAQDpAOMQAQEA+wDjEAEBAQ0A4xABAQEfAOMQAQEBMQDjEAEBAUMA4xABAQFVAOMQAQEBZwDjEAEBAXkA4xABAQAIAOSgAQMAswDkBAEDAOkA5KABAwGUAOQEAQMABwDlogUBALIA5QYFAQDoAOWiBQEBkwDlBgUBAAIA6r8BAwDKAOoBARAAywDqAQERAMwA6gwBDwDYAOoBAREA2QDqAQEQAOMA6r8BAwABAOvBAgIAyQDrAQESAMoA6wEBAwDLAOsOAQwA2QDrAQEDANoA6wEBEgDiAOvBAgIAyQDsAQIEAMoA7AEBAgDLAOwOAQYA2QDsAQECANoA7AECBAABAO3BAQQAygDtEAEEAOIA7cEBBADJAO4BARkAygDuAQEaAMsA7gEBGwDMAO4BARwAzQDuCAETANUA7gUBHADaAO4BAR0AuwDvLQEEAOgA7wEBHgC7APABEA0AvADwAQEHAL0A8CkBAwDmAPABARAA5wDwARAOAOgA8AEQCwC8APEBDgMAvQDxKA4BAOUA8QEOCQDmAPEBDgMAvAD/AQEHAL0A/ykBAwDmAP8BARAAuwEAAQIUALwBAAECFQC9AQApAgIA5gEAAQIWAOcBAAECFwDoAQABAhgAuwECLQEEAOgBAgEBHgB6AQSwAQQAegEFAasEAHsBBa4BAwEpAQUBqwQAewEGAacDAHwBBqwEAQEoAQYBpwMAfAEKBaIBAIEBCqIBAwEjAQoFUQEAgQELAUMDAIIBC6ACBQEiAQsBQwMAggENoAQCAIIBEQY8AgCIAREIAQoAkAERAzwCAJMBETYBBQDJARFZBgIAiAESAQcKAIkBEgYBBQCPARIBBwoAkwESATUFAJQBEhABAgCkARICNAYApgESEAECALYBEgI0BgC4ARIQAQIAyAESATUFAIkBEwEFBQCKARMBAQMAiwETAgEFAI0BEwEBAwCOARMBBQUAlAETEA8AAKYBExAPAAC4ARMQDwAAigEUAQEKAIsBFAICAwCNARQBAQoAigEVAQEFAI0BFQEBBQCKARYBAQMAiwEWAgEKAI0BFgEBAwCKARcBAgoAiwEXAgEFAI0BFwECCgDJARczDQIA/AEXCAEKAQQBFwgJAgEMARcIAQoBFAEXDjYCAIkBGAEBCgCLARgCAQoAjgEYAQEKAPwBGAEHCgD9ARgGAgUBAwEYAQcKAQwBGAEHCgENARgGAgUBEwEYAQcKAIgBGQg0AgD9ARoCAQUA/wEaAgIDAQEBGgIBBQENARoCAQUBDwEaAgIDAREBGgIBBQD9ARsBAwUA/gEbAQEDAQEBGwEBAwECARsBAwUBDQEbAQMFAQ4BGwEBAwERARsBAQMBEgEbAQMFAP4BHAQBCgEOARwEAQoA/gEdBAEFAQ4BHQQBBQD9AR4GAQoBDQEeBgEKAPwBHwgBAgEMAR8IAQIA/AEgGAEFAPwBIQEXBQD9ASEWAQIBEwEhARcFAJQBIhACBgCmASIQAgYAuAEiEAIGAP0BIhYVAACUASQQAQIApgEkEAECALgBJBABAgDJASQnBgIA8AEkARAFAPEBJAsBAgCUASUQDwAApgElEA8AALgBJRAPAADxASUBDgUA8gElCgECAPIBJgEMBQDzASYJAQIA8wEnAQoFAPQBJwgBAgD0ASgBCAUA9QEoBwECAPUBKQEGBQD2ASkGAQIAyQEqBCMCAM0BKiMEBQD2ASoBBAUA9wEqBQECAPcBKwECBQD4ASsEIgIA9wEtASACAM0BLiMfAgD2AS4BHwIA9QEvAR4CAPQBMAEdAgDzATEBHAIA8gEyARsCAPEBMwEaAgCUATQQAgYApgE0EAIGALgBNBACBgDwATQBGQIAlAE2EAECAKYBNhABAgC4ATYQAQIAlAE3EA8AAKYBNxAPAAC4ATcQDwAA/QE3FgEFAPwBOBgBAgD8ATkIFAIBBAE5CAEKAQwBOQgUAgEEAToBBwoBBQE6BgIFAQsBOgEHCgEFATwBBAUBBgE8BAEDAQoBPAEEBQEGAT0BAQoBBwE9AgEDAQkBPQEBCgEGAT4BAgUBBwE+AgEKAQkBPgECBQEHAT8CAQUBBQFABgEKAQQBQQgMAgCUAUY0AQUAkwFHNgYCAIIBTaABAwCBAU6iDQEAgQFbAVEBAIIBW6IBAwEkAVsEUQEAggFcATUDAIMBXBABAgCTAVwCNAEAlQFcEAECAKUBXAI0AQCnAVwQAQIAtwFcAjQBALkBXBABAgDJAVwCNAEAywFcEAECANsBXAI0AQDdAVwQAQIA7QFcAjQBAO8BXBABAgD/AVwCNAEBAQFcEAECAREBXAI0AQETAVwQAQIBIwFcATUDAIMBXRAPAACVAV0QDwAApwFdEA8AALkBXRAPAADLAV0QDwAA3QFdEA8AAO8BXRAPAAEBAV0QDwABEwFdEA8AAIMBbBACAQCVAWwQAgEApwFsEAIBALkBbBACAQDLAWwQAgEA3QFsEAIBAO8BbBACAQEBAWwQAgEBEwFsEAIBAIMBbhABAgCVAW4QAQIApwFuEAECALkBbhABAgDLAW4QAQIA3QFuEAECAO8BbhABAgEBAW4QAQIBEwFuEAECAIMBbxAPAACVAW8QDwAApwFvEA8AALkBbxAPAADLAW8QDwAA3QFvEA8AAO8BbxAPAAEBAW8QDwABEwFvEA8AAIMBfhACAQCVAX4QAgEApwF+EAIBALkBfhACAQDLAX4QAgEA3QF+EAIBAO8BfhACAQEBAX4QAgEBEwF+EAIBAIMBgBABAgCVAYAQAQIApwGAEAECALkBgBABAgDLAYAQAQIA3QGAEAECAO8BgBABAgEBAYAQAQIBEwGAEAECAIMBgRAPAACVAYEQDwAApwGBEA8AALkBgRAPAADLAYEQDwAA3QGBEA8AAO8BgRAPAAEBAYEQDwABEwGBEA8AAIMBkKABAwCCAZGiBAEAggGVogEDAIIBlgERAwCDAZYQAQIAkwGWAhABAJUBlhABAgClAZYCEAEApwGWEAECALcBlgIQAQC5AZYQAQIAyQGWAhABAMsBlhABAgDbAZYCEAEA3QGWEAECAO0BlgIQAQDvAZYQAQIA/wGWAhABAQEBlhABAgERAZYCEAEBEwGWEAECASMBlgERAwCDAZcQDwAAlQGXEA8AAKcBlxAPAAC5AZcQDwAAywGXEA8AAN0BlxAPAADvAZcQDwABAQGXEA8AARMBlxAPAACDAaagAQMAggGnogUBAHwBrKwBAwB7Aa2uAgYAewGvrgEE";
    public static final Skin BG = new Skin(420, 432, PAL_BG, DAT_BG);

    private static final int[] PAL_PATTERN = {
            0xFF9A9FB4, 0xFFCBCCD4, 0xFFF2F2F2, 0xFFADB0C4, 0xFF696D88, 0xFF413F54
    };
    private static final String DAT_PATTERN =
            "AAAAABYYAQAWAABoAQIAfgAADSwBAIsAABIBAgCdAAAJLAEAFgABAUMCABcAAWYCBAB9AAEBMwIAiwABARECAIwAARABAACcAAEBEQIAjAACEA8DABcAA2ZAAACMABEQAQIAiwASEhoBAAAAGAEsAQABABgUAQUAFQAYASwBAAEAGQETBQACABkSAQIAFAAZARMFAAIAGgERAgADABoQAQAAEwAaARECAAMAGxAPAwADACoQAQIAAgArEgEFAAEALBQYAQB+ACwKBwEAiAAsGAECAKAALAYYAQCIAC0BBwIAiQAtFgIEAJ8ALQEXAgCJAC8WFAAAfgAzCgECAH0ANAwCBAB9ADYMBgAAfQA8DAECAH0APQEHAgB+AD0KBwEAiAA9AQcCABcAQ2YBAgCJAEMWAQI=";
    public static final Skin PATTERN = new Skin(166, 68, PAL_PATTERN, DAT_PATTERN);

    private static final int[] PAL_BTN = {
            0xFF9A9FB4, 0xFF413F54, 0xFFADB0C4, 0xFF696D88
    };
    private static final String DAT_BTN =
            "AAAAAAwBAQAAAAEBCwEAAQABCgECAAsAAQELAQABAAIBBwIAAgACCAYAAAoAAgEHAgACAAgIAQIAAQAJCgIDAAEACwoBAQ==";
    public static final Skin BTN = new Skin(12, 12, PAL_BTN, DAT_BTN);

    private static final int[] PAL_BTN_PUSH = {
            0xFF9CD3FF, 0xFF413F54, 0xFFDAFFFF, 0xFF708CBA
    };
    private static final String DAT_BTN_PUSH =
            "AAAAAQwBAQAAAAIBCgEAAQACCgECAAsAAgEKAQABAAMBBwIAAgADCAYAAAoAAwEHAgACAAkIAQIAAQAKCgEDAAEACwoBAQ==";
    public static final Skin BTN_PUSH = new Skin(12, 12, PAL_BTN_PUSH, DAT_BTN_PUSH);

    private static final int[] PAL_TAB_ON = {
            0xFFCBCCD4, 0xFFF2F2F2, 0xFF413F54, 0xFF878FA5
    };
    private static final String DAT_TAB_ON =
            "AAAAAAEWAAABAAABAgEAAgAAFAECAAIAARMBAQAVAAEBFQIAAQACExAAABQAAgERAQABABITAQEAAQATAQMBAAIAExMCAwACABUTAQI=";
    public static final Skin TAB_ON = new Skin(22, 22, PAL_TAB_ON, DAT_TAB_ON);

    private static final int[] PAL_TAB_OFF = {
            0xFF878FA5, 0xFF413F54, 0xFFADB0C4, 0xFF9A9FB4, 0xFFCBCCD4, 0xFFF2F2F2
    };
    private static final String DAT_TAB_OFF =
            "AAAAAAEWBAABAAABFgUAAgAAFAEBAAIAAQEVAQADAAESAQIAFQABARUBAAMAAhEQAAAUAAIBEQIAAwASEQECAAMAExICAwADABUSAQE=";
    public static final Skin TAB_OFF = new Skin(22, 22, PAL_TAB_OFF, DAT_TAB_OFF);

    private static final int[] PAL_CHK_WH = {
            0xFF413F54, 0xFF9CD3FF, 0xFF9A9FB4, 0xFFADB0C4, 0xFF696D88, 0xFFDAFFFF
    };
    private static final String DAT_CHK_WH =
            "AAIAAAwBAAAAAAEDAQAAAwABCgEDAA0AAQkBAAAAAAIBCgAAAQACAQkEAAIAAgEKAAADAAIBBwMABAACCAYCAAwAAgEHAwANAAIBCgAADgACBwIBABUAAgEKAAAOAAQCBwEAEAAEAQUFABEABAQHAQAEAAgIAQMAAwAJCgIEABAACQECAQABAAsBAQAAAwALCgEAAA4ACwcBAA==";
    public static final Skin CHK_WH = new Skin(22, 12, PAL_CHK_WH, DAT_CHK_WH);

    private static final int[] PAL_CHK_AE = {
            0xFF413F54, 0xFF9CD3FF, 0xFF9A9FB4, 0xFFADB0C4, 0xFF696D88, 0xFFDAFFFF
    };
    private static final String DAT_CHK_AE =
            "AAgAAAwBAAAAAAEJAQAACQABCgEDABMAAQMBAAAAAAIBCgAAAQACBwIBAAgAAgEKAAAJAAIBBwMACgACCAYCABIAAgEHAwATAAIBCgAAFAACAQkEABUAAgEKAAABAAQEBwEABQAEAQUFAAYABAIHAQAKAAgIAQMABQAJAQIBAAkACQoCBAABAAsHAQAACQALCgEAABQACwEBAA==";
    public static final Skin CHK_AE = new Skin(22, 12, PAL_CHK_AE, DAT_CHK_AE);

    private static final int[] PAL_THUMB = {
            0xFF49495F, 0xFF9A9FB4, 0xFFAFB5CA, 0xFF9499AE, 0xFF9FA6BB, 0xFF969BB0, 0xFF8E95AA, 0xFFB6BBD0,
            0xFFBFC4D9, 0xFF9DA1B8, 0xFF646985, 0xFF616682, 0x8248475C, 0xA7444257, 0xFFCACFE4, 0xFFBBBFD3,
            0x86434156
    };
    private static final String DAT_THUMB =
            "AAAAAAEBDAABAAAIAQAACQAAAQENAAAAAQEKAAABAAEBAQ4AAgABAQEPAAMAAQQBBwAHAAEBAQ8ACAABAQEIAAkAAQEKAAABAAIBAQcAAgACAQEJAAMAAgQBBAAHAAIBAQkACAACAQEHAAEAAwEFAgACAAMBAQYAAwADBAEFAAcAAwEBBgAIAAMBBQIAAgAEAQMDAAMABAQDAQAHAAQBAwMAAgAHAQEGAAMABwQBBQAHAAcBAQYAAQAIAQEIAAIACAYBAgAIAAgBAQgAAQAJAQEBAAIACQEBCQADAAkEAQUABwAJAQEJAAgACQEBAQABAAoCAQoAAwAKBAELAAcACgIBCgAAAAsBARAAAQALCAEAAAkACwEBEA==";
    public static final Skin THUMB = new Skin(10, 12, PAL_THUMB, DAT_THUMB);

}