modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecolonies"
type="required"
versionRange="[1.1.1299,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ae2"
type="required"
versionRange="[19.2.17,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="domum_ornamentum"
type="required"
versionRange="[1.0.230,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="structurize"
type="required"
versionRange="[1.0.820,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="blockui"
type="required"
versionRange="[1.0.211,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="guideme"
type="required"
versionRange="[21.1.15,)"
ordering="AFTER"

[[dependencies.${mod_id}]]
modId="jade"
type="optional"
versionRange="[15.0.0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="refinedstorage"
type="optional"
versionRange="[2.0.5,)"
ordering="AFTER"
side="BOTH"
