/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableMap
 *  net.minecraft.resources.ResourceLocation
 */
package appeng.api.ids;

import appeng.api.util.AEColor;
import com.google.common.collect.ImmutableMap;
import java.util.Map;
import net.minecraft.resources.ResourceLocation;

public final class AEItemIds {
    public static final ResourceLocation NETWORK_TOOL = AEItemIds.id("network_tool");
    public static final ResourceLocation VIEW_CELL = AEItemIds.id("view_cell");
    public static final ResourceLocation MEMORY_CARD = AEItemIds.id("memory_card");
    public static final ResourceLocation BLANK_PATTERN = AEItemIds.id("blank_pattern");
    public static final ResourceLocation CRAFTING_PATTERN = AEItemIds.id("crafting_pattern");
    public static final ResourceLocation PROCESSING_PATTERN = AEItemIds.id("processing_pattern");
    public static final ResourceLocation SMITHING_TABLE_PATTERN = AEItemIds.id("smithing_table_pattern");
    public static final ResourceLocation STONECUTTING_PATTERN = AEItemIds.id("stonecutting_pattern");
    public static final ResourceLocation MISSING_CONTENT = AEItemIds.id("missing_content");
    public static final ResourceLocation ENTROPY_MANIPULATOR = AEItemIds.id("entropy_manipulator");
    public static final ResourceLocation MATTER_CANNON = AEItemIds.id("matter_cannon");
    public static final ResourceLocation CHARGED_STAFF = AEItemIds.id("charged_staff");
    public static final ResourceLocation COLOR_APPLICATOR = AEItemIds.id("color_applicator");
    public static final ResourceLocation WIRELESS_TERMINAL = AEItemIds.id("wireless_terminal");
    public static final ResourceLocation WIRELESS_CRAFTING_TERMINAL = AEItemIds.id("wireless_crafting_terminal");
    public static final ResourceLocation WRAPPED_GENERIC_STACK = AEItemIds.id("wrapped_generic_stack");
    public static final ResourceLocation FACADE = AEItemIds.id("facade");
    public static final ResourceLocation STORAGE_CELL_1K = AEItemIds.id("storage_cell_1k");
    public static final ResourceLocation STORAGE_CELL_4K = AEItemIds.id("storage_cell_4k");
    public static final ResourceLocation STORAGE_CELL_16K = AEItemIds.id("storage_cell_16k");
    public static final ResourceLocation STORAGE_CELL_64K = AEItemIds.id("storage_cell_64k");
    public static final ResourceLocation STORAGE_CELL_256K = AEItemIds.id("storage_cell_256k");
    public static final ResourceLocation ITEM_CELL_1K = AEItemIds.id("item_storage_cell_1k");
    public static final ResourceLocation ITEM_CELL_4K = AEItemIds.id("item_storage_cell_4k");
    public static final ResourceLocation ITEM_CELL_16K = AEItemIds.id("item_storage_cell_16k");
    public static final ResourceLocation ITEM_CELL_64K = AEItemIds.id("item_storage_cell_64k");
    public static final ResourceLocation ITEM_CELL_256K = AEItemIds.id("item_storage_cell_256k");
    public static final ResourceLocation FLUID_CELL_1K = AEItemIds.id("fluid_storage_cell_1k");
    public static final ResourceLocation FLUID_CELL_4K = AEItemIds.id("fluid_storage_cell_4k");
    public static final ResourceLocation FLUID_CELL_16K = AEItemIds.id("fluid_storage_cell_16k");
    public static final ResourceLocation FLUID_CELL_64K = AEItemIds.id("fluid_storage_cell_64k");
    public static final ResourceLocation FLUID_CELL_256K = AEItemIds.id("fluid_storage_cell_256k");
    public static final ResourceLocation SPATIAL_CELL_2 = AEItemIds.id("spatial_storage_cell_2");
    public static final ResourceLocation SPATIAL_CELL_16 = AEItemIds.id("spatial_storage_cell_16");
    public static final ResourceLocation SPATIAL_CELL_128 = AEItemIds.id("spatial_storage_cell_128");
    public static final ResourceLocation CREATIVE_CELL = AEItemIds.id("creative_storage_cell");
    public static final ResourceLocation PORTABLE_ITEM_CELL1K = AEItemIds.id("portable_item_cell_1k");
    public static final ResourceLocation PORTABLE_ITEM_CELL4K = AEItemIds.id("portable_item_cell_4k");
    public static final ResourceLocation PORTABLE_ITEM_CELL16K = AEItemIds.id("portable_item_cell_16k");
    public static final ResourceLocation PORTABLE_ITEM_CELL64K = AEItemIds.id("portable_item_cell_64k");
    public static final ResourceLocation PORTABLE_ITEM_CELL256K = AEItemIds.id("portable_item_cell_256k");
    public static final ResourceLocation PORTABLE_FLUID_CELL1K = AEItemIds.id("portable_fluid_cell_1k");
    public static final ResourceLocation PORTABLE_FLUID_CELL4K = AEItemIds.id("portable_fluid_cell_4k");
    public static final ResourceLocation PORTABLE_FLUID_CELL16K = AEItemIds.id("portable_fluid_cell_16k");
    public static final ResourceLocation PORTABLE_FLUID_CELL64K = AEItemIds.id("portable_fluid_cell_64k");
    public static final ResourceLocation PORTABLE_FLUID_CELL256K = AEItemIds.id("portable_fluid_cell_256k");
    public static final ResourceLocation COLORED_LUMEN_PAINT_BALL_WHITE = AEItemIds.id("white_lumen_paint_ball");
    public static final ResourceLocation COLORED_LUMEN_PAINT_BALL_ORANGE = AEItemIds.id("orange_lumen_paint_ball");
    public static final ResourceLocation COLORED_LUMEN_PAINT_BALL_MAGENTA = AEItemIds.id("magenta_lumen_paint_ball");
    public static final ResourceLocation COLORED_LUMEN_PAINT_BALL_LIGHT_BLUE = AEItemIds.id("light_blue_lumen_paint_ball");
    public static final ResourceLocation COLORED_LUMEN_PAINT_BALL_YELLOW = AEItemIds.id("yellow_lumen_paint_ball");
    public static final ResourceLocation COLORED_LUMEN_PAINT_BALL_LIME = AEItemIds.id("lime_lumen_paint_ball");
    public static final ResourceLocation COLORED_LUMEN_PAINT_BALL_PINK = AEItemIds.id("pink_lumen_paint_ball");
    public static final ResourceLocation COLORED_LUMEN_PAINT_BALL_GRAY = AEItemIds.id("gray_lumen_paint_ball");
    public static final ResourceLocation COLORED_LUMEN_PAINT_BALL_LIGHT_GRAY = AEItemIds.id("light_gray_lumen_paint_ball");
    public static final ResourceLocation COLORED_LUMEN_PAINT_BALL_CYAN = AEItemIds.id("cyan_lumen_paint_ball");
    public static final ResourceLocation COLORED_LUMEN_PAINT_BALL_PURPLE = AEItemIds.id("purple_lumen_paint_ball");
    public static final ResourceLocation COLORED_LUMEN_PAINT_BALL_BLUE = AEItemIds.id("blue_lumen_paint_ball");
    public static final ResourceLocation COLORED_LUMEN_PAINT_BALL_BROWN = AEItemIds.id("brown_lumen_paint_ball");
    public static final ResourceLocation COLORED_LUMEN_PAINT_BALL_GREEN = AEItemIds.id("green_lumen_paint_ball");
    public static final ResourceLocation COLORED_LUMEN_PAINT_BALL_RED = AEItemIds.id("red_lumen_paint_ball");
    public static final ResourceLocation COLORED_LUMEN_PAINT_BALL_BLACK = AEItemIds.id("black_lumen_paint_ball");
    public static final Map<AEColor, ResourceLocation> COLORED_LUMEN_PAINT_BALL = ImmutableMap.builder().put((Object)AEColor.WHITE, (Object)COLORED_LUMEN_PAINT_BALL_WHITE).put((Object)AEColor.ORANGE, (Object)COLORED_LUMEN_PAINT_BALL_ORANGE).put((Object)AEColor.MAGENTA, (Object)COLORED_LUMEN_PAINT_BALL_MAGENTA).put((Object)AEColor.LIGHT_BLUE, (Object)COLORED_LUMEN_PAINT_BALL_LIGHT_BLUE).put((Object)AEColor.YELLOW, (Object)COLORED_LUMEN_PAINT_BALL_YELLOW).put((Object)AEColor.LIME, (Object)COLORED_LUMEN_PAINT_BALL_LIME).put((Object)AEColor.PINK, (Object)COLORED_LUMEN_PAINT_BALL_PINK).put((Object)AEColor.GRAY, (Object)COLORED_LUMEN_PAINT_BALL_GRAY).put((Object)AEColor.LIGHT_GRAY, (Object)COLORED_LUMEN_PAINT_BALL_LIGHT_GRAY).put((Object)AEColor.CYAN, (Object)COLORED_LUMEN_PAINT_BALL_CYAN).put((Object)AEColor.PURPLE, (Object)COLORED_LUMEN_PAINT_BALL_PURPLE).put((Object)AEColor.BLUE, (Object)COLORED_LUMEN_PAINT_BALL_BLUE).put((Object)AEColor.BROWN, (Object)COLORED_LUMEN_PAINT_BALL_BROWN).put((Object)AEColor.GREEN, (Object)COLORED_LUMEN_PAINT_BALL_GREEN).put((Object)AEColor.RED, (Object)COLORED_LUMEN_PAINT_BALL_RED).put((Object)AEColor.BLACK, (Object)COLORED_LUMEN_PAINT_BALL_BLACK).build();
    public static final ResourceLocation COLORED_PAINT_BALL_WHITE = AEItemIds.id("white_paint_ball");
    public static final ResourceLocation COLORED_PAINT_BALL_ORANGE = AEItemIds.id("orange_paint_ball");
    public static final ResourceLocation COLORED_PAINT_BALL_MAGENTA = AEItemIds.id("magenta_paint_ball");
    public static final ResourceLocation COLORED_PAINT_BALL_LIGHT_BLUE = AEItemIds.id("light_blue_paint_ball");
    public static final ResourceLocation COLORED_PAINT_BALL_YELLOW = AEItemIds.id("yellow_paint_ball");
    public static final ResourceLocation COLORED_PAINT_BALL_LIME = AEItemIds.id("lime_paint_ball");
    public static final ResourceLocation COLORED_PAINT_BALL_PINK = AEItemIds.id("pink_paint_ball");
    public static final ResourceLocation COLORED_PAINT_BALL_GRAY = AEItemIds.id("gray_paint_ball");
    public static final ResourceLocation COLORED_PAINT_BALL_LIGHT_GRAY = AEItemIds.id("light_gray_paint_ball");
    public static final ResourceLocation COLORED_PAINT_BALL_CYAN = AEItemIds.id("cyan_paint_ball");
    public static final ResourceLocation COLORED_PAINT_BALL_PURPLE = AEItemIds.id("purple_paint_ball");
    public static final ResourceLocation COLORED_PAINT_BALL_BLUE = AEItemIds.id("blue_paint_ball");
    public static final ResourceLocation COLORED_PAINT_BALL_BROWN = AEItemIds.id("brown_paint_ball");
    public static final ResourceLocation COLORED_PAINT_BALL_GREEN = AEItemIds.id("green_paint_ball");
    public static final ResourceLocation COLORED_PAINT_BALL_RED = AEItemIds.id("red_paint_ball");
    public static final ResourceLocation COLORED_PAINT_BALL_BLACK = AEItemIds.id("black_paint_ball");
    public static final Map<AEColor, ResourceLocation> COLORED_PAINT_BALL = ImmutableMap.builder().put((Object)AEColor.WHITE, (Object)COLORED_PAINT_BALL_WHITE).put((Object)AEColor.ORANGE, (Object)COLORED_PAINT_BALL_ORANGE).put((Object)AEColor.MAGENTA, (Object)COLORED_PAINT_BALL_MAGENTA).put((Object)AEColor.LIGHT_BLUE, (Object)COLORED_PAINT_BALL_LIGHT_BLUE).put((Object)AEColor.YELLOW, (Object)COLORED_PAINT_BALL_YELLOW).put((Object)AEColor.LIME, (Object)COLORED_PAINT_BALL_LIME).put((Object)AEColor.PINK, (Object)COLORED_PAINT_BALL_PINK).put((Object)AEColor.GRAY, (Object)COLORED_PAINT_BALL_GRAY).put((Object)AEColor.LIGHT_GRAY, (Object)COLORED_PAINT_BALL_LIGHT_GRAY).put((Object)AEColor.CYAN, (Object)COLORED_PAINT_BALL_CYAN).put((Object)AEColor.PURPLE, (Object)COLORED_PAINT_BALL_PURPLE).put((Object)AEColor.BLUE, (Object)COLORED_PAINT_BALL_BLUE).put((Object)AEColor.BROWN, (Object)COLORED_PAINT_BALL_BROWN).put((Object)AEColor.GREEN, (Object)COLORED_PAINT_BALL_GREEN).put((Object)AEColor.RED, (Object)COLORED_PAINT_BALL_RED).put((Object)AEColor.BLACK, (Object)COLORED_PAINT_BALL_BLACK).build();
    public static final ResourceLocation CERTUS_QUARTZ_AXE = AEItemIds.id("certus_quartz_axe");
    public static final ResourceLocation CERTUS_QUARTZ_HOE = AEItemIds.id("certus_quartz_hoe");
    public static final ResourceLocation CERTUS_QUARTZ_SHOVEL = AEItemIds.id("certus_quartz_shovel");
    public static final ResourceLocation CERTUS_QUARTZ_PICK = AEItemIds.id("certus_quartz_pickaxe");
    public static final ResourceLocation CERTUS_QUARTZ_SWORD = AEItemIds.id("certus_quartz_sword");
    public static final ResourceLocation CERTUS_QUARTZ_WRENCH = AEItemIds.id("certus_quartz_wrench");
    public static final ResourceLocation CERTUS_QUARTZ_KNIFE = AEItemIds.id("certus_quartz_cutting_knife");
    public static final ResourceLocation NETHER_QUARTZ_AXE = AEItemIds.id("nether_quartz_axe");
    public static final ResourceLocation NETHER_QUARTZ_HOE = AEItemIds.id("nether_quartz_hoe");
    public static final ResourceLocation NETHER_QUARTZ_SHOVEL = AEItemIds.id("nether_quartz_shovel");
    public static final ResourceLocation NETHER_QUARTZ_PICK = AEItemIds.id("nether_quartz_pickaxe");
    public static final ResourceLocation NETHER_QUARTZ_SWORD = AEItemIds.id("nether_quartz_sword");
    public static final ResourceLocation NETHER_QUARTZ_WRENCH = AEItemIds.id("nether_quartz_wrench");
    public static final ResourceLocation NETHER_QUARTZ_KNIFE = AEItemIds.id("nether_quartz_cutting_knife");
    public static final ResourceLocation FLUIX_UPGRADE_SMITHING_TEMPLATE = AEItemIds.id("fluix_upgrade_smithing_template");
    public static final ResourceLocation FLUIX_AXE = AEItemIds.id("fluix_axe");
    public static final ResourceLocation FLUIX_HOE = AEItemIds.id("fluix_hoe");
    public static final ResourceLocation FLUIX_SHOVEL = AEItemIds.id("fluix_shovel");
    public static final ResourceLocation FLUIX_PICK = AEItemIds.id("fluix_pickaxe");
    public static final ResourceLocation FLUIX_SWORD = AEItemIds.id("fluix_sword");
    public static final ResourceLocation METEORITE_COMPASS = AEItemIds.id("meteorite_compass");
    public static final ResourceLocation CERTUS_QUARTZ_CRYSTAL = AEItemIds.id("certus_quartz_crystal");
    public static final ResourceLocation CERTUS_QUARTZ_CRYSTAL_CHARGED = AEItemIds.id("charged_certus_quartz_crystal");
    public static final ResourceLocation CERTUS_QUARTZ_DUST = AEItemIds.id("certus_quartz_dust");
    public static final ResourceLocation SILICON = AEItemIds.id("silicon");
    public static final ResourceLocation MATTER_BALL = AEItemIds.id("matter_ball");
    public static final ResourceLocation FLUIX_CRYSTAL = AEItemIds.id("fluix_crystal");
    public static final ResourceLocation FLUIX_DUST = AEItemIds.id("fluix_dust");
    public static final ResourceLocation FLUIX_PEARL = AEItemIds.id("fluix_pearl");
    public static final ResourceLocation PURIFIED_CERTUS_QUARTZ_CRYSTAL = AEItemIds.id("purified_certus_quartz_crystal");
    public static final ResourceLocation PURIFIED_NETHER_QUARTZ_CRYSTAL = AEItemIds.id("purified_nether_quartz_crystal");
    public static final ResourceLocation PURIFIED_FLUIX_CRYSTAL = AEItemIds.id("purified_fluix_crystal");
    public static final ResourceLocation CALCULATION_PROCESSOR_PRESS = AEItemIds.id("calculation_processor_press");
    public static final ResourceLocation ENGINEERING_PROCESSOR_PRESS = AEItemIds.id("engineering_processor_press");
    public static final ResourceLocation LOGIC_PROCESSOR_PRESS = AEItemIds.id("logic_processor_press");
    public static final ResourceLocation CALCULATION_PROCESSOR_PRINT = AEItemIds.id("printed_calculation_processor");
    public static final ResourceLocation ENGINEERING_PROCESSOR_PRINT = AEItemIds.id("printed_engineering_processor");
    public static final ResourceLocation LOGIC_PROCESSOR_PRINT = AEItemIds.id("printed_logic_processor");
    public static final ResourceLocation SILICON_PRESS = AEItemIds.id("silicon_press");
    public static final ResourceLocation SILICON_PRINT = AEItemIds.id("printed_silicon");
    public static final ResourceLocation NAME_PRESS = AEItemIds.id("name_press");
    public static final ResourceLocation LOGIC_PROCESSOR = AEItemIds.id("logic_processor");
    public static final ResourceLocation CALCULATION_PROCESSOR = AEItemIds.id("calculation_processor");
    public static final ResourceLocation ENGINEERING_PROCESSOR = AEItemIds.id("engineering_processor");
    public static final ResourceLocation BASIC_CARD = AEItemIds.id("basic_card");
    public static final ResourceLocation REDSTONE_CARD = AEItemIds.id("redstone_card");
    public static final ResourceLocation CAPACITY_CARD = AEItemIds.id("capacity_card");
    public static final ResourceLocation VOID_CARD = AEItemIds.id("void_card");
    public static final ResourceLocation ADVANCED_CARD = AEItemIds.id("advanced_card");
    public static final ResourceLocation FUZZY_CARD = AEItemIds.id("fuzzy_card");
    public static final ResourceLocation SPEED_CARD = AEItemIds.id("speed_card");
    public static final ResourceLocation INVERTER_CARD = AEItemIds.id("inverter_card");
    public static final ResourceLocation CRAFTING_CARD = AEItemIds.id("crafting_card");
    public static final ResourceLocation ENERGY_CARD = AEItemIds.id("energy_card");
    public static final ResourceLocation EQUAL_DISTRIBUTION_CARD = AEItemIds.id("equal_distribution_card");
    public static final ResourceLocation SPATIAL_2_CELL_COMPONENT = AEItemIds.id("spatial_cell_component_2");
    public static final ResourceLocation SPATIAL_16_CELL_COMPONENT = AEItemIds.id("spatial_cell_component_16");
    public static final ResourceLocation SPATIAL_128_CELL_COMPONENT = AEItemIds.id("spatial_cell_component_128");
    public static final ResourceLocation CELL_COMPONENT_1K = AEItemIds.id("cell_component_1k");
    public static final ResourceLocation CELL_COMPONENT_4K = AEItemIds.id("cell_component_4k");
    public static final ResourceLocation CELL_COMPONENT_16K = AEItemIds.id("cell_component_16k");
    public static final ResourceLocation CELL_COMPONENT_64K = AEItemIds.id("cell_component_64k");
    public static final ResourceLocation CELL_COMPONENT_256K = AEItemIds.id("cell_component_256k");
    public static final ResourceLocation ITEM_CELL_HOUSING = AEItemIds.id("item_cell_housing");
    public static final ResourceLocation FLUID_CELL_HOUSING = AEItemIds.id("fluid_cell_housing");
    public static final ResourceLocation WIRELESS_RECEIVER = AEItemIds.id("wireless_receiver");
    public static final ResourceLocation WIRELESS_BOOSTER = AEItemIds.id("wireless_booster");
    public static final ResourceLocation FORMATION_CORE = AEItemIds.id("formation_core");
    public static final ResourceLocation ANNIHILATION_CORE = AEItemIds.id("annihilation_core");
    public static final ResourceLocation SKY_DUST = AEItemIds.id("sky_dust");
    public static final ResourceLocation GUIDE = AEItemIds.id("guide");
    public static final ResourceLocation ENDER_DUST = AEItemIds.id("ender_dust");
    public static final ResourceLocation SINGULARITY = AEItemIds.id("singularity");
    public static final ResourceLocation QUANTUM_ENTANGLED_SINGULARITY = AEItemIds.id("quantum_entangled_singularity");

    private static ResourceLocation id(String id) {
        return ResourceLocation.fromNamespaceAndPath((String)"ae2", (String)id);
    }
}

